commitment_cost: 0.25
dropout: 0.0
ema_decay: 0.99
latent_dim: 128
lr: 0.0004
max_iters: 2584950
model_type: hierachical
name: hierachical-hierachical-hierachical--patch_size_64-pre_num_channels_32-num_channels_64-latent_dim_128-num_embeddings_256-num_residual_blocks_3-num_transformer_blocks_0
num_channels: 64
num_embeddings: 256
num_heads: 4
num_residual_blocks: 3
num_transformer_blocks: 0
patch_channels: 1
patch_depth: -1
patch_size: 64
pre_num_channels: 32
resume_checkpoint: {}
warmup: 387742.5
weight_decay: 0.0001
